### ISSUE TITLE
Can’t unzip dark theme file

### ISSUE THREAD

**Issue by jimp412** [jeffThompson/DarkArduinoTheme#27] opened 2019-04-11 03:31 UTC
Arduino ide sketch text is so light it is nearly impossible to read. Tried loading dark theme. Zip file gets many errors when unzipping.

**Comment by jeffThompson** [comment] 2019-04-11 13:22
Could you be more specific about what errors you get? What platform are you on? What software are you using to unzip?

**Comment by jimp412** [comment] 2019-04-11 14:04
Extracting to:c:arduino\"Use Path: yesOverwrite files: no
Error: .travis.yml     File is a directoryError: .travis.yml     Error opening fileExtracting: .travis.ymlWarning: .travis.yml failed the CRC CheckError: .travis.yml     File fails CRC checkError: README.md     File is a directoryError: README.md     Error opening fileExtracting: README.mdWarning: README.md failed the CRC CheckError: README.md     File fails CRC checkError: screenshot.jpg     File is a directoryError: screenshot.jpg     Error opening fileExtracting: screenshot.jpgWarning: screenshot.jpg failed the 
Running Windows 10
Ultimate Zip
I have used this unzip software many times without a problem.
Thanks.......Jim
    On Thursday, April 11, 2019, 9:22:48 AM EDT, Jeff Thompson <notifications@github.com> wrote:  
 
 
Could you be more specific about what errors you get? What platform are you on? What software are you using to unzip?

**Comment by jeffThompson** [comment] 2019-04-11 14:07
Hmm sounds like an error with the zip that Github generates. Did you try re-downloading it and unzipping? I'm afraid this isn't an issue with the repo, so I'm going to close this.

**Comment by jimp412** [comment] 2019-04-11 14:09
Jeff, never mind. I just got it to unzip. I was just being stupid with the destination directory name.

Thanks....Jim

**Comment by jimp412** [comment] 2019-04-11 14:40
Jeff, unzipped OK.

Backed up /lib/theme

Copied unzipped files to /lib/theme

Restarted 

Still no Dark theme

Jim...

**Comment by jeffThompson** [comment] 2019-04-11 16:26
Which version of Arduino are you on? Which OS?

**Comment by jeffThompson** [comment] 2019-05-21 13:33
I'm going to close this, since the issue is not about unzipping the theme. If you're still having problems, feel free to open a new issue.

**Closed by jeffThompson** 2019-05-21 13:33 UTC
